"""Migration."""
# Generated by Django 3.2.18 on 2023-03-10 11:25

from django.db import migrations


class Migration(migrations.Migration):
    """Migration."""

    dependencies = [
        ('recipes', '0002_auto_20230309_0308'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipeingredient',
            old_name='quantity',
            new_name='amount',
        ),
    ]
