"""Migration."""
# Generated by Django 3.2.18 on 2023-03-10 14:59

from django.db import migrations, models


class Migration(migrations.Migration):
    """Migration."""

    dependencies = [
        ('recipes', '0003_rename_quantity_recipeingredient_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='name',
            field=models.CharField(help_text='Укажите название ингредиента', max_length=100, unique=True, verbose_name='Название ингредиента'),
        ),
    ]
