"""Migration."""
# Generated by Django 3.2.18 on 2023-03-10 15:16

from django.db import migrations, models


class Migration(migrations.Migration):
    """Migration."""

    dependencies = [
        ('recipes', '0004_alter_ingredient_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='measurement_unit',
            field=models.CharField(help_text='Укажите ед.изм.', max_length=50, verbose_name='Единица измерения'),
        ),
    ]
