"""Migration."""
# Generated by Django 3.2.18 on 2023-03-11 09:47

from django.db import migrations, models


class Migration(migrations.Migration):
    """Migration."""

    dependencies = [
        ('recipes', '0005_alter_ingredient_measurement_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='name',
            field=models.CharField(help_text='Укажите название ингредиента', max_length=100, verbose_name='Название ингредиента'),
        ),
    ]
